services:
  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ghcr.io/contentautomator/distributorapi:main
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./api/dist/:/home/node/dist/:rw
  test:
    image: curlimages/curl:latest
    command: ["sh", "-c", "curl -X POST http://api:3000/api/v1/render-video -H 'Content-Type: application/json' -d '{\"prompt\": \"Sunset over the mountains\"}'"]
    depends_on:
      api:
        condition: service_healthy
  ws:
    # build:
    #   context: ./wscat/
    #   dockerfile: Dockerfile
    image: ghcr.io/qtvhao/wscat:master
    command: ["sh", "-c", "wscat -c ws://api:3000 -m 'Hello from the client!'"]
    depends_on:
      api:
        condition: service_healthy
